/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebsiteRouteImport } from './routes/website'
import { Route as VideoRouteImport } from './routes/video'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ImageRouteImport } from './routes/image'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWebsiteRouteImport } from './routes/api/website'
import { Route as ApiResearchRouteImport } from './routes/api/research'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'
import { Route as ApiCodeResearchRouteImport } from './routes/api/code-research'

const WebsiteRoute = WebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoRoute = VideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageRoute = ImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebsiteRoute = ApiWebsiteRouteImport.update({
  id: '/api/website',
  path: '/api/website',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResearchRoute = ApiResearchRouteImport.update({
  id: '/api/research',
  path: '/api/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCodeResearchRoute = ApiCodeResearchRouteImport.update({
  id: '/api/code-research',
  path: '/api/code-research',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/image': typeof ImageRoute
  '/research': typeof ResearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/video': typeof VideoRoute
  '/website': typeof WebsiteRoute
  '/api/code-research': typeof ApiCodeResearchRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/research': typeof ApiResearchRoute
  '/api/website': typeof ApiWebsiteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/image': typeof ImageRoute
  '/research': typeof ResearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/video': typeof VideoRoute
  '/website': typeof WebsiteRoute
  '/api/code-research': typeof ApiCodeResearchRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/research': typeof ApiResearchRoute
  '/api/website': typeof ApiWebsiteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/image': typeof ImageRoute
  '/research': typeof ResearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/video': typeof VideoRoute
  '/website': typeof WebsiteRoute
  '/api/code-research': typeof ApiCodeResearchRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/research': typeof ApiResearchRoute
  '/api/website': typeof ApiWebsiteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/image'
    | '/research'
    | '/sitemap.xml'
    | '/video'
    | '/website'
    | '/api/code-research'
    | '/api/generate-image'
    | '/api/research'
    | '/api/website'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/image'
    | '/research'
    | '/sitemap.xml'
    | '/video'
    | '/website'
    | '/api/code-research'
    | '/api/generate-image'
    | '/api/research'
    | '/api/website'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/image'
    | '/research'
    | '/sitemap.xml'
    | '/video'
    | '/website'
    | '/api/code-research'
    | '/api/generate-image'
    | '/api/research'
    | '/api/website'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  ImageRoute: typeof ImageRoute
  ResearchRoute: typeof ResearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VideoRoute: typeof VideoRoute
  WebsiteRoute: typeof WebsiteRoute
  ApiCodeResearchRoute: typeof ApiCodeResearchRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
  ApiResearchRoute: typeof ApiResearchRoute
  ApiWebsiteRoute: typeof ApiWebsiteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/website': {
      id: '/website'
      path: '/website'
      fullPath: '/website'
      preLoaderRoute: typeof WebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video': {
      id: '/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image': {
      id: '/image'
      path: '/image'
      fullPath: '/image'
      preLoaderRoute: typeof ImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/website': {
      id: '/api/website'
      path: '/api/website'
      fullPath: '/api/website'
      preLoaderRoute: typeof ApiWebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/research': {
      id: '/api/research'
      path: '/api/research'
      fullPath: '/api/research'
      preLoaderRoute: typeof ApiResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/code-research': {
      id: '/api/code-research'
      path: '/api/code-research'
      fullPath: '/api/code-research'
      preLoaderRoute: typeof ApiCodeResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  ImageRoute: ImageRoute,
  ResearchRoute: ResearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VideoRoute: VideoRoute,
  WebsiteRoute: WebsiteRoute,
  ApiCodeResearchRoute: ApiCodeResearchRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
  ApiResearchRoute: ApiResearchRoute,
  ApiWebsiteRoute: ApiWebsiteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
